export const articleCarrusel = [
  '<article id="carouselExampleDark" class="container carousel carousel-dark slide m-6 p-6">',
  '<div class="carousel-indicators">',
  '<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"',
  'aria-current="true" aria-label="Slide 1"></button>',
  '<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>',
  '<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>',
  '</div>',
  '<div class="carousel-inner">',
  '<div class="carousel-item active" data-bs-interval="10000">',
  '<img src="https://images.unsplash.com/photo-1433838552652-f9a46b332c40?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="rounded" style="height: 500px; aspect-ratio: 16/9; width: 100%" alt="..." />',
  '</div>',
  '<div class="carousel-item" data-bs-interval="2000">',
  '<img src="https://images.unsplash.com/photo-1519987428647-d3abc85fcd01?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="rounded" style="height: 500px; aspect-ratio: 16/9; width: 100%" alt="..." />',
  '</div>',
  '<div class="carousel-item">',
  '<img src="https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="rounded" style="height: 500px; aspect-ratio: 16/9; width: 100%" alt="..." />',
  '</div>',
  '</div>',
  '<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">',
  '<span class="carousel-control-prev-icon" aria-hidden="true"></span>',
  '<span class="visually-hidden">Previous</span>',
  '</button>',
  '<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">',
  '<span class="carousel-control-next-icon" aria-hidden="true"></span>',
  '<span class="visually-hidden">Next</span>',
  '</button>',
  '</article>'
].join('')
