export const aboutContent = [
  '  <header class="col-sm-12 text-center" id="about">',
  '    <h2 class="text-capitalize fs-2">NOSOTROS</h2>',
  '  </header>',
  '<section class="row text-black justify-content-center">',
  '<article class="col-sm-8 col-md-5 m-5 rounded p-5 shadow bg-white">',
  '<header>',
  '<h3>Mision</h3>',
  '</header>',
  '<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore, est, neque quasi quia enim consectetur',
  'corporis optio esse expedita facere illum culpa nobis omnis ratione labore error cum fuga! Eaque.</p>',
  '</article>',
  '<article class="col-sm-8 col-md-5 m-5 rounded p-5 shadow bg-white">',
  '<header>',
  '<h3>Vision</h3>',
  '</header>',
  '<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore, est, neque quasi quia enim consectetur',
  'corporis optio esse expedita facere illum culpa nobis omnis ratione labore error cum fuga! Eaque.</p>',
  '</article>',
  '<article class="col-sm-8 col-md-5 m-5 rounded p-5 shadow bg-white">',
  '<header>',
  '<h3>Objetivos</h3>',
  '</header>',
  '<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore, est, neque quasi quia enim consectetur',
  'corporis optio esse expedita facere illum culpa nobis omnis ratione labore error cum fuga! Eaque.</p>',
  '</article>',
  '<article class="col-sm-8 col-md-5 m-5 rounded p-5 shadow bg-white">',
  '<header>',
  '<h3>Valores</h3>',
  '</header>',
  '<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore, est, neque quasi quia enim consectetur',
  'corporis optio esse expedita facere illum culpa nobis omnis ratione labore error cum fuga! Eaque.</p>',
  '</article>',
  '</section>'
].join('')
