export const pageOfertas = [
  '<div class="container">',
  '  <div class="col text-center">',
  '    <span class="fw-bold fs-3">Encuentra nuestras mejores promociones</span>',
  '    <h1 class="text-capitalize fs-2">OFERTAS</h1>',
  '  </div>',
  '  <div class="row justify-content-center">',
  '    <div class="col-md-3 row justify-content-center">',
  '      <article class="card-ofertas">',
  '        <div class="card-body bg-img-card">',
  '          <span class="discount" id="discount">HASTA 40% OFF</span>',
  '        </div>',
  '        <h3 class="card-title">BARÚ</h3>',
  '        <p class="card-text">Cartagena, Colombia</p>',
  '        <p class="price-before">ANTES: $1.000.000</p>',
  '        <p class="price-now-title">DESDE:</p>',
  '        <p class="price-now">$600.000 <span class="iva">Iva Inc.</span></p>',
  '        <p class="info-nights">2 noches/persona</p>',
  '        <button class="btn btn-primary text-center">RESERVAR AHORA</button>',
  '      </article>',
  '    </div>',
  '  </div>',
  '</div>'
].join('')
// RESUBIDO
